/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDo;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        HashMap <Integer, ListItem> toDoList = new HashMap<Integer, ListItem>();
        ListItem itemOne = new ListItem();
       // itemOne.setName("Task Name");
       // itemOne.setDueDate("01/01/1111");
       // itemOne.setInProg("Yes");
       // itemOne.setCompleted("Yes");

        getMainMenu();

    }

    public static void  getMainMenu() {

        System.out.println("          Main Menu          ");
        System.out.println("1. Open ToDo List");
        System.out.println("2. Display ToDO Items");
        System.out.println("3. Edit ToDo Items");
        System.out.println("4. Delete ToDo Items");
        System.out.println("5. Save ToDO List");
        System.out.println("6. Exit");
        System.out.println("");

        readConsole();
    }

    private static void readConsole() {

        System.out.println("Please enter 1-6 based off of the menu above:");
        Scanner scanner = new Scanner(System.in);
        int z = scanner.nextInt();

        try {
            switch (z) {
                case 1:
                    openList();
                    break;
                case 2:
                    displayList();
                    break;
                case 3:
                    editList();
                    break;
                case 4:
                    deleteItem();
                    break;
                case 5:
                    saveList();
                    break;
                case 6:
                    exit();
                    break;
                default:
                    System.out.println("Invalid response, please try again using numbers 1 though 6 only:");
                    readConsole();
                    break;
            }
        } catch (java.util.InputMismatchException e){
            System.out.println("Invalid response, please try again using numbers 1 though 6 only:");
        }
    }

    private static void exit() {
        System.exit(1);

        getMainMenu();
    }

    private static void saveList() {
        System.out.println("save");

        getMainMenu();
    }

    private static void deleteItem() {
        System.out.println("del");

        getMainMenu();
    }

    private static void editList() {
        System.out.println("edit");



        getMainMenu();
    }

    private static void displayList() {
        System.out.println("Empty list, please add an item");
        editList();
        getMainMenu();
    }

    private static void openList() {
        System.out.println("open");

        getMainMenu();
    }


}
